x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'https://loki-querier:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

x-minio-common: &minio-common
  image: minio/minio:RELEASE.2024-04-06T05-26-02Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    restart: unless-stopped
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --enable-feature=exemplar-storage
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=remote-write-receiver
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus-config.yaml
      - ./config/prometheus/rules/:/etc/prometheus/rules
      - /home/config/prometheus/web.yml:/etc/prometheus/web.yml
      - ./config/minio/certs/:/etc/prometheus/
      - /etc/localtime:/etc/localtime:ro
      - ./config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
    ports:
      - "9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.9
    logging: *default-logging
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SECURITY_ADMIN_USER=grafana
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/data:/var/lib/grafana
      - ./config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - ./config/minio/certs/:/etc/grafana/
      - /etc/localtime:/etc/localtime:ro
    command: >
      /bin/sh -c "
        update-ca-certificates &&
        exec grafana -c /etc/grafana/grafana.ini &&
        grafana-cli plugins install yesoreyeram-boomtheme-panel"


  mimir1:
    container_name: mimir1
    image: grafana/mimir:2.10.1
    mem_limit: 2g

    restart: unless-stopped
    command:
      - -ingester.native-histograms-ingestion-enabled=true
      - -config.file=/etc/mimir.yaml
      - -server.http-tls-cert-path=/etc/public.crt
      - -server.http-tls-key-path=/etc/private.np.key
      - -server.http-tls-ca-path=/etc/rootca.crt
      - -server.http-tls-client-auth=VerifyClientCertIfGiven
      - -validation.max-label-names-per-series=60
    ports:
      - "9009"
      - "7946"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mimir/mimir.yml:/etc/mimir.yaml
      - ./config/minio/certs/rootca.crt:/etc/rootca.crt
      - ./config/minio/certs/:/etc/

  mimir2:
    container_name: mimir2
    mem_limit: 2g
    image: grafana/mimir:2.10.1

    restart: unless-stopped
    command:
      - -ingester.native-histograms-ingestion-enabled=true
      - -config.file=/etc/mimir.yaml
      - -server.http-tls-cert-path=/etc/public.crt
      - -server.http-tls-key-path=/etc/private.np.key
      - -server.http-tls-ca-path=/etc/rootca.crt
      - -validation.max-label-names-per-series=60
      - -server.http-tls-client-auth=VerifyClientCertIfGiven
    ports:
      - "9009"
      - "7046"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mimir/mimir.yml:/etc/mimir.yaml
      - ./config/minio/certs/rootca.crt:/etc/
      - ./config/minio/certs/:/etc/

  mimir3:
    container_name: mimir3
    image: grafana/mimir:2.10.1
    mem_limit: 2g

    restart: unless-stopped
    command:
      - -ingester.native-histograms-ingestion-enabled=true
      - -config.file=/etc/mimir.yaml
      - -server.http-tls-cert-path=/etc/public.crt
      - -server.http-tls-key-path=/etc/private.np.key
      - -server.http-tls-ca-path=/etc/rootca.crt
      - -validation.max-label-names-per-series=60
      - -server.http-tls-client-auth=VerifyClientCertIfGiven
    ports:
      - "9009"
      - "7946"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mimir/mimir.yml:/etc/mimir.yaml
      - ./config/minio/certs/rootca.crt:/etc/
      - ./config/minio/certs/:/etc/

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --log.level=debug
    volumes:
      - /home/config/alertmanager/:/etc/alertmanager/
      - /etc/localtime:/etc/localtime:ro

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter

    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/:/etc/tls/
      - ./config/node-exporter/web.yml:/etc/config/web.yml
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.config.file=/etc/config/web.yml'
    ports:
      - "9100:9100"

  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    ports:
      - "9000:9000"
    volumes:
      - data1-1:/data1
      - data1-2:/data2
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/rootca.crt:/root/.minio/certs/CAs/rootca.crt
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/rootca.crt:/root/.minio/certs/CAs/rootca.crt
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/rootca.crt:/root/.minio/certs/CAs/rootca.crt
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/rootca.crt:/root/.minio/certs/CAs/rootca.crt
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always

  nginx-1:
    image: nginx:1.25.5
    container_name: nginx-1
    restart: unless-stopped
    ports:
      - "440:440"
      - "441:441"
      - "442:442"
      - "443:443"
      - "444:444"
      - "445:445"
      - "446:446"
      - "447:447"
      - "448:448"
      - "449:449"
    volumes:
      - ./config/nginx-1/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx-1/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/minio/certs/:/etc/nginx/certs/
      - /etc/localtime:/etc/localtime:ro


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    ports:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command: --housekeeping_interval=10s

  registry:
    image: registry:latest
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000"
    volumes:
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/registry/config.yml:/etc/docker/registry/config.yml
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/public.crt
      REGISTRY_HTTP_TLS_KEY: /etc/private.np.key

  fluentd:
    image: fluentd:latest
    container_name: fluentd
    volumes:
      - /var/log:/var/host/log
      - /var/log/windows:/var/host/log/windows
      - /etc/localtime:/etc/localtime:ro
      - /home/config/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /home/config/minio/certs/public.crt:/fluentd/etc/public.crt
      - /home/config/minio/certs/private.np.key:/fluentd/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
    command: >
      /bin/sh -c "
        update-ca-certificates &&
        exec fluentd -c /fluentd/etc/fluent.conf"

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail/config.yml","-config.expand-env=true"]
    volumes:
      - /var/log:/var/log
      - /var/log/journal/:/var/log/journal/
      - /etc/machine-id:/etc/machine-id
      - /home/config/promtail/promtail.yml:/etc/promtail/config.yml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/promtail/public.crt
      - /home/config/minio/certs/private.np.key:/etc/promtail/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/10.200.100.209_sg.log:/home/10.200.100.209_sg.log
    ports:
      - 1514:1514/udp

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    container_name: snmp-exporter
    expose:1
      - "9115"
    command:
    - '--config.file=/etc/blackbox/blackbox.yml'
    - '--web.config.file=/etc/config/web.yml'
    volumes:
    - /home/config//blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    - /home/config/minio/certs/public.crt:/etc/public.crt
    - /home/config/minio/certs/private.np.key:/etc/private.np.key
    - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    - ./config/blackbox/web.yml:/etc/config/web.yml

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld
    command:
     - "--mysqld.username=${MYSQL_USER}:${MYSQL_PASSWORD}"
     - "--mysqld.address=${MYSQL_HOST}:${MYSQL_PORT}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/mysql/mysql.sock:/tmp/mysql.sock
    expose:
      - "9104"


volumes:
  tempo-data:
  grafana-data:
  mimir1-data:
  mimir2-data:
  mimir3-data:
  prometheus-data:
  alertmanager-data:
  minio-data:
  docker-registry-data:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
