services:
  tempo-distributor:
    image: grafana/tempo:2.4.1
    command: "-target=distributor -config.file=/etc/tempo.yaml"
    container_name: tempo-distributor
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
    restart: always
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
      - "4318"
      - "7946"
    networks:
      - home_default

  tempo-ingester-0:
    mem_limit: 2g
    image: grafana/tempo:2.4.1
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    container_name: tempo-ingester-0
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
    restart: always
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
      - "7946"
    networks:
      - home_default

  tempo-ingester-1:
    mem_limit: 2g
    image: grafana/tempo:2.4.1
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    container_name: tempo-ingester-1
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
    restart: always
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
      - "7946"
    networks:
      - home_default

  tempo-ingester-2:
    mem_limit: 2g
    image: grafana/tempo:2.4.1
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    container_name: tempo-ingester-2
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
    restart: always
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
      - "7946"
    networks:
      - home_default

  tempo-querier:
    image: grafana/tempo:2.4.1
    command: "-target=querier -config.file=/etc/tempo.yaml -log.level=debug"
    container_name: tempo-querier
    restart: always
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
    networks:
      - home_default

  tempo-compactor:
    image: grafana/tempo:2.4.1
    command: "-target=compactor -config.file=/etc/tempo.yaml"
    container_name: tempo-compactor
    restart: always
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
    networks:
      - home_default

  tempo-metrics-generator:
    image: grafana/tempo:2.4.1
    command: "-target=metrics-generator -config.file=/etc/tempo.yaml"
    container_name: tempo-metrics-generator
    restart: always
    environment:
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
    networks:
      - home_default

  tempo-query-frontend:
    image: grafana/tempo:2.4.1
    command: "-target=query-frontend -config.file=/etc/tempo.yaml -log.level=debug"
    restart: always
    environment:
      - TEMPO_HTTP_TLS_CERT_FILE=/etc/public.crt
      - TEMPO_HTTP_TLS_KEY_FILE=/etc/private.np.key
      - TEMPO_HTTP_TLS_CA_FILE=/etc/ssl/certs/rootca.crt
    container_name: tempo-query-frontend
    volumes:
      - /home/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /etc/localtime:/etc/localtime:ro
      - /home/config/minio/certs/public.crt:/etc/public.crt
      - /home/config/minio/certs/private.np.key:/etc/private.np.key
      - /home/config/minio/certs/rootca.crt:/usr/local/share/ca-certificates/rootca.crt
      - /home/config/minio/certs/rootca.crt:/etc/ssl/certs/rootca.crt
    ports:
      - "3200"
      - "9095"
    networks:
      - home_default

  nginx-2:
    image: nginx:1.25.5
    container_name: nginx-2
    restart: unless-stopped
    ports:
      - "50088:50080" # docker registry(optional)
      - "50089:50089" # docker registry(optional)
      - "50090:50090" # docker registry(optional)
    volumes:
      - /home/rpm5:/home/rpm5
      - /home/rpm4:/home/rpm4
      - /home/rpm3:/home/rpm3
      - /home/config/nginx-2/nginx.conf:/etc/nginx/nginx.conf
      - /home/config/nginx-2/default.conf:/etc/nginx/conf.d/default.conf
      - /home/config/minio/certs/public.crt:/etc/nginx/certs/public.crt
      - /home/config/minio/certs/private.np.key:/etc/nginx/certs/private.np.key
      - /home/config/minio/certs/rootca.crt:/etc/nginx/certs/rootca.crt
      - /etc/localtime:/etc/localtime:ro
    networks:
      - home_default

networks:
  home_default:
    external: true
