multitenancy_enabled: true
activity_tracker: {}
alertmanager: {}
alertmanager_storage:
  backend: local

server:
  http_listen_port: 9009
  http_tls_config:
    cert_file: /etc/public.crt               # TLS 인증서 파일
    key_file: /etc/private.np.key            # TLS 개인 키 파일
    client_ca_file: /etc/rootca.crt          # 클라이언트 인증서 검증을 위한 CA 파일
    client_auth_type: VerifyClientCertIfGiven  # 클라이언트 인증 선택적 검증
  log_level: warn                             # 로그 레벨 (warn, info, debug)
  grpc_server_max_recv_msg_size: 104857600   # gRPC 서버 최대 수신 메시지 크기 (100MB)
  grpc_server_max_send_msg_size: 104857600   # gRPC 서버 최대 전송 메시지 크기 (100MB)
  grpc_server_max_concurrent_streams: 1000   # 동시 gRPC 스트림 최대 개수

  storage:
    backend: s3
    s3:
      endpoint: insert-ip
      region: null
      secret_access_key: ${S3_SECRET_ACCESS_KEY}  # 환경변수로 보안 강화
      access_key_id: ${S3_ACCESS_KEY_ID}         # 환경변수로 보안 강화

blocks_storage:
  backend: s3
  s3:
    endpoint: insert-ip
    bucket_name: mimir
    region: null
    secret_access_key: ${S3_SECRET_ACCESS_KEY}  # 환경변수 사용
    access_key_id: ${S3_ACCESS_KEY_ID}         # 환경변수 사용
    http:
      insecure_skip_verify: false               # HTTPS 인증서 검증 비활성화
  tsdb:
    retention_period: 168h                      # 데이터 보존 기간 (7일)
    dir: /data/ingester                         # TSDB 저장 디렉토리

ruler_storage:
  backend: filesystem
  local:
    directory: /tmp/mimir/rules

distributor:
  pool:
    health_check_ingesters: true  # Ingesters 상태 확인 활성화

ingester:
  instance_limits:
    max_series: 1200000            # 최대 시계열 개수 설정
  ring:
    final_sleep: 0s
    kvstore:
      store: memberlist            # 클러스터 멤버 관리 방식 (memberlist)
    min_ready_duration: 0s
    num_tokens: 512                # 토큰 개수 (분산을 위해 설정)
    replication_factor: 1           # 복제 계수 (1이면 단일 복제)

memberlist:
  abort_if_cluster_join_fails: false  # 클러스터 조인 실패 시 종료 여부
  join_members:
    - mimir1:7946
    - mimir2:7946
    - mimir3:7946
    - mimir4:7946
    - mimir5:7946
    - mimir6:7946

compactor:
  sharding_ring:
    kvstore:
      store: memberlist  # Compactor도 클러스터 관리에 memberlist 사용

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://alertmanager:9093/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s

limits:
  ingestion_burst_size: 500000  # 데이터 수집 최대 버스트 크기
  ingestion_rate: 250000        # 초당 데이터 수집 속도 제한

querier:
  max_concurrent: 16               # 동시 쿼리 실행 수 제한
  active_query_tracker_dir: /tmp/mimir_queries  # 쿼리 트래킹 저장소

query_frontend:
  max_outstanding_per_tenant: 1000  # 각 테넌트당 최대 요청 수

auth:
  basic_auth_users:
    admin: ${ADMIN_PASSWORD}  # 환경변수를 사용하여 비밀번호 관리
  api_keys:
    - my-secure-api-key       # API 키 인증 (선택 사항)
